apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-tools

resources:
- configmap.yaml
- secret-externalsecret.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app: jenkins-notify
  version: v1.0.0

images:
- name: harbor.devflux.ru/jenkins-notify
  newTag: latest
