apiVersion: v1
kind: Secret
metadata:
  name: jenkins-notify-secret
  namespace: devops-tools
type: Opaque
data:
  # Base64. Токен бота для отправки в Telegram (6749424559:AAF...)
  telegram-bot-token: "Njc0OTQyNDU1OTpBQUZrbVJCdEkyaG13UXQ3ZEJTSk8zQ01fdnhXNm5IMU5Rbw=="
  # echo -n "your-telegram-chat-id" | base64  
  telegram-chat-id: "MTMyMDg2NTkzMw=="
  # echo -n "your-api-keys" | base64 (comma-separated list)
  api-keys: "MjNBc2E5RGpFMWFlR0FQZFNwR1BKUXhlbFF6dXRTNUhyNjU1NGtJaVRBd2VWOEtJTFA5eWY4MkxOVWhaNUYwNg=="
