apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: alertmanager-telegram-secret
    creationPolicy: Owner
  data:
    - secretKey: telegram-bot-token
      remoteRef:
        key: monitoring/alertmanager-telegram
        property: telegram-bot-token
    - secretKey: telegram-chat-id
      remoteRef:
        key: monitoring/alertmanager-telegram
        property: telegram-chat-id
