apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-vpn-subscription
  annotations:
    force-sync: "2026-03-04T00:00:00Z"
  namespace: openclaw
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: openclaw-vpn-subscription
    creationPolicy: Owner
  data:
    - secretKey: subscription_url
      remoteRef:
        key: openclaw/proxy
        property: subscription_url
