apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dns-notify-bot-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: dns-notify-bot-secret
    creationPolicy: Owner
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        key: secret/dns-notify-bot
        property: bot_token
    - secretKey: ALLOWED_USER_IDS
      remoteRef:
        key: secret/dns-notify-bot
        property: allowed_user_ids
    - secretKey: DB_URL
      remoteRef:
        key: secret/dns-notify-bot
        property: db_url
