apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
          name: web
        - containerPort: 5679
          name: broker
        env:
        - name: N8N_BASIC_AUTH_ACTIVE
          value: "true"
        - name: N8N_BASIC_AUTH_USER
          value: "n8n"
        - name: WEBHOOK_URL
          value: "https://n8n.devflux.ru/"
        - name: GENERIC_TIMEZONE
          value: "Europe/Moscow"
        - name: N8N_PROTOCOL
          value: "https"
        - name: N8N_RUNNERS_ENABLED
          value: "true"
        - name: N8N_RUNNERS_MODE
          value: "external"
        - name: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: N8N_RUNNERS_BROKER_PORT
          value: "5679"
        - name: N8N_NATIVE_PYTHON_RUNNER
          value: "true"
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_BASIC_AUTH_PASSWORD
        - name: N8N_RUNNERS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: n8n-secret
              key: N8N_RUNNERS_AUTH_TOKEN
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
        - name: kanban-backups
          mountPath: /backups/kanban
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-pvc
      - name: kanban-backups
        hostPath:
          path: /backups/kanban
          type: Directory
