apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - secret-externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - task-runner-deployment.yaml
  - task-runner-service.yaml
  - ingress.yaml

configMapGenerator:
  - name: n8n-task-runner-config
    namespace: n8n
    files:
      - n8n-task-runners.json=task-runners/n8n-task-runners.json
