apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - secret-externalsecret.yaml
  - task-runner-configmap.yaml
  - deployment.yaml
  - service.yaml
  - task-runner-deployment.yaml
  - task-runner-service.yaml
  - ingress.yaml
