apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-secret
  annotations:
    force-sync: "2026-03-04T00:00:00Z"
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: n8n-secret
    creationPolicy: Owner
  data:
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        key: n8n/auth
        property: N8N_BASIC_AUTH_PASSWORD
    - secretKey: N8N_RUNNERS_AUTH_TOKEN
      remoteRef:
        key: n8n/auth
        property: N8N_RUNNERS_AUTH_TOKEN
