apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: playerok
  labels:
    app: frontend
    environment: prod
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      environment: prod
  template:
    metadata:
      labels:
        app: frontend
        environment: prod
        component: frontend
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: frontend
          image: harbor.devflux.ru/playerok-devflux/frontend-prod:1
          imagePullPolicy: Always
          env:
            - name: NGINX_RESOLVER
              value: "10.152.183.10"
            - name: FRONTEND_SEO_ENABLED
              value: "true"
            - name: FRONTEND_SEARCH_INDEXING
              value: "false"
            - name: FRONTEND_SITE_URL
              value: "https://devflux.ru"
            - name: BACKEND_HOST
              value: "backend.playerok.svc.cluster.local"
            - name: BACKEND_UPSTREAM
              value: "backend.playerok.svc.cluster.local:8000"
            - name: ARTIFACT_SERVER_UPSTREAM
              value: "backend.playerok.svc.cluster.local:8000"
          ports:
            - name: http
              containerPort: 80
