apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devflux

resources:
  - config-artifact-server.yaml
  - secrets-externalsecret.yaml
  - deployment-artifact-server.yaml
  - service-artifact-server.yaml
  - ingress-artifact-server.yaml
  - hpa-artifact-server.yaml
  - servicemonitor-artifact-server.yaml
  - pdb-artifact-server.yaml
