apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devflux-secrets
  labels:
    app: artifact-server
    component: artifacts
    environment: prod
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: devflux-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: devflux/artifact-server
        property: DATABASE_URL
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: devflux/artifact-server
        property: JWT_SECRET_KEY
    - secretKey: S3_ENDPOINT_URL
      remoteRef:
        key: devflux/artifact-server
        property: S3_ENDPOINT_URL
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: devflux/artifact-server
        property: S3_ACCESS_KEY
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: devflux/artifact-server
        property: S3_SECRET_KEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry
  labels:
    app: artifact-server
    component: artifacts
    environment: prod
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: devflux/artifact-server
        property: HARBOR_DOCKERCONFIGJSON
