apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: common-apps
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitoring.devflux.io/enabled: "true"
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
