apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jenkins-notify
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespaceSelector:
    matchNames:
      - devops-tools
  selector:
    matchLabels:
      app: jenkins-notify
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
