apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasks-devflux-data
  namespace: tasks-devflux-dev
  labels:
    app: tasks-devflux
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi