apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: couchdb-secret
    creationPolicy: Owner
  data:
    - secretKey: COUCHDB_USER
      remoteRef:
        key: databases/couchdb
        property: COUCHDB_USER
    - secretKey: COUCHDB_PASSWORD
      remoteRef:
        key: databases/couchdb
        property: COUCHDB_PASSWORD
