apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    environment: dev
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      environment: dev
  template:
    metadata:
      labels:
        app: frontend
        environment: dev
        component: frontend
    spec:
      imagePullSecrets:
        - name: harbor-registry
      containers:
        - name: frontend
          image: harbor.devflux.ru/playerok-devflux/frontend-dev:v0.31.1-dev.297-sha.6ddbf0898e7d
          imagePullPolicy: Always
          env:
            - name: NGINX_RESOLVER
              value: "10.152.183.10"
            - name: BACKEND_HOST
              value: "backend.playerok-dev.svc.cluster.local"
            - name: BACKEND_UPSTREAM
              value: "backend.playerok-dev.svc.cluster.local:8000"
            - name: ARTIFACT_SERVER_UPSTREAM
              value: "artifact-server.playerok-dev.svc.cluster.local:8080"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 256Mi
              cpu: 250m
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
