apiVersion: apps/v1
kind: Deployment
metadata:
  name: playerok-metadata-collector
  labels:
    app: playerok-metadata-collector
    environment: dev
    component: worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: playerok-metadata-collector
      environment: dev
  template:
    metadata:
      labels:
        app: playerok-metadata-collector
        environment: dev
        component: worker
    spec:
      imagePullSecrets:
        - name: harbor-registry
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: playerok-metadata-collector
          image: harbor.devflux.ru/playerok-devflux/playerok-metadata-collector-dev:v0.58.0-dev.570-sha.da6f5f249846
          imagePullPolicy: Always
          ports:
            - name: metrics
              containerPort: 9102
          envFrom:
            - configMapRef:
                name: playerok-metadata-collector
            - secretRef:
                name: playerok-metadata-collector
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 20
