apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    environment: dev
    component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        environment: dev
        component: api
    spec:
      imagePullSecrets:
        - name: harbor-registry
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: backend
          image: harbor.devflux.ru/playerok-devflux/backend-dev:v0.8.0-dev.190-sha.172c8a2cc7f4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: playerok-secrets
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 35
            periodSeconds: 5
