apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playerok-dev

resources:
  - config-backend.yaml
  - config-artifact-server.yaml
  - secrets-externalsecret.yaml
  - secrets-artifact-server-externalsecret.yaml
  - portabase.yaml
  - deployment-backend.yaml
  - deployment-email-worker.yaml
  - deployment-artifact-server.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-artifact-server.yaml
  - service-frontend.yaml
  - ingress-frontend.yaml
  - ingress-artifact-server.yaml
  - job-backend-migrations.yaml
