apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: playerok-metadata-backend
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: playerok-metadata-backend
    creationPolicy: Owner
  data:
    - secretKey: PLAYEROK_METADATA_COLLECTOR_TOKEN
      remoteRef:
        key: playerok-dev/playerok
        property: PLAYEROK_METADATA_COLLECTOR_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: playerok-metadata-collector
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: playerok-metadata-collector
    creationPolicy: Owner
  data:
    - secretKey: PLAYEROK_METADATA_COLLECTOR_TOKEN
      remoteRef:
        key: playerok-dev/playerok
        property: PLAYEROK_METADATA_COLLECTOR_TOKEN
    - secretKey: PLAYEROK_METADATA_PLAYEROK_TOKEN
      remoteRef:
        key: playerok-dev/playerok
        property: PLAYEROK_METADATA_PLAYEROK_TOKEN
    - secretKey: PLAYEROK_METADATA_PLAYEROK_USER_AGENT
      remoteRef:
        key: playerok-dev/playerok
        property: PLAYEROK_METADATA_PLAYEROK_USER_AGENT
