apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  annotations:
    force-sync: "2026-03-04T00:00:00Z"
  namespace: argocd
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
  data:
    - secretKey: telegram-token
      remoteRef:
        key: argocd/notifications
        property: telegram-token
    - secretKey: telegram-chat-id
      remoteRef:
        key: argocd/notifications
        property: telegram-chat-id
