apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
data:
  # echo -n "replace-with-argocd-telegram-bot-token" | base64
  telegram-token: cmVwbGFjZS13aXRoLWFyZ29jZC10ZWxlZ3JhbS1ib3QtdG9rZW4=
  # echo -n "123456789" | base64
  telegram-chat-id: MTIzNDU2Nzg5
