apiVersion: v1
kind: Namespace
metadata:
  name: obsidian-sync
  labels:
    name: obsidian-sync
    app: obsidian-sync
    environment: prod
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
