apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: obsidian-sync
  labels:
    app: obsidian-sync
    environment: prod
    component: couchdb
spec:
  type: ClusterIP
  selector:
    app: obsidian-sync
    environment: prod
    component: couchdb
  ports:
    - name: http
      port: 5984
      targetPort: http
      protocol: TCP
