apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-metrics-basic-auth
  namespace: mail
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: stalwart-metrics-basic-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: monitoring/stalwart-metrics
        property: username
    - secretKey: password
      remoteRef:
        key: monitoring/stalwart-metrics
        property: password
