apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kv-group

resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - web.yaml
  - mail.yaml
  - pdb.yaml
  - ingress.yaml
  - ingress-kvteam.yaml

images:
  - name: harbor.devflux.ru/kv-group/api
    newTag: 14-7657e481d459
  - name: harbor.devflux.ru/kv-group/web
    newTag: 14-7657e481d459