apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: outline

resources:
  - namespace.yaml
  - pvc.yaml
  - secret-externalsecret.yaml
  - postgres.yaml
  - redis.yaml
  - dex.yaml
  - outline.yaml
  - ingress.yaml
