apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: outline-secrets
  labels:
    app.kubernetes.io/name: outline
spec:
  refreshInterval: 2m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: outline-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: outline/config
        property: SECRET_KEY
    - secretKey: UTILS_SECRET
      remoteRef:
        key: outline/config
        property: UTILS_SECRET
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: outline/config
        property: POSTGRES_PASSWORD
    - secretKey: DATABASE_URL
      remoteRef:
        key: outline/config
        property: DATABASE_URL
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: outline/config
        property: OIDC_CLIENT_SECRET
    - secretKey: DEX_CONFIG
      remoteRef:
        key: outline/config
        property: DEX_CONFIG
