apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
type: Opaque
data:
  # echo -n "8683355191:AAGA0YMkyt4vZP5oKIawzOJcgLCGVOpNPXs" | base64
  telegram-bot-token: ODY4MzM1NTE5MTpBQUdBMFlNa3l0NHZaUDVvS0lhd3pPSmNnTENHVk9wTlBYcw==
  # echo -n "1320865933" | base64
  telegram-chat-id: MTMyMDg2NTkzMw==
