apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-telegram-secret
  namespace: monitoring
type: Opaque
data:
  # echo -n "replace-with-telegram-bot-token" | base64
  telegram-bot-token: ODY4MzM1NTE5MTpBQUdBMFlNa3l0NHZaUDVvS0lhd3pPSmNnTENHVk9wTlBYcw==
  # echo -n "123456789" | base64
  telegram-chat-id: MTMyMDg2NTkzMw==
