apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
data:
  # echo -n "sunkist" | base64
  admin-user: c3Vua2lzdA==
  # echo -n "20172010Egor" | base64
  admin-password: MjAxNzIwMTBFZ29y
