apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
data:
  # echo -n "admin" | base64
  admin-user: c3Vua2lzdA==
  # echo -n "change-me-strong-password" | base64
  admin-password: MjAxNzIwMTBFZ29y
