apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
type: Opaque
data:
  # echo -n "admin" | base64
  admin-user: YWRtaW4=
  # echo -n "change-me-strong-password" | base64
  admin-password: Y2hhbmdlLW1lLXN0cm9uZy1wYXNzd29yZA==
