apiVersion: v1
kind: Secret
metadata:
  name: omnirouter-basic-auth
  namespace: omnirouter
type: Opaque
data:
  # sunkist:20172010.
  # Используйте: echo -n 'sunkist:20172010.' для входа
  auth: c3Vua2lzdDokYXByMSRaSkZZc3p2dyRiTW9Zd0dwL3NiRjVhUkxYVDM0MW4x
---
apiVersion: v1
kind: Secret
metadata:
  name: omnirouter-env
  namespace: omnirouter
type: Opaque
stringData:
  OMNIROUTE_MEMORY_MB: "512"
  # Добавьте сюда ваши API ключи для провайдеров
  # ANTHROPIC_API_KEY: "sk-ant-..."
  # OPENAI_API_KEY: "sk-..."
