apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-pc-power
  annotations:
    force-sync: "2026-03-04T00:00:00Z"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: home-assistant-pc-power-secret
    creationPolicy: Owner
  data:
    - secretKey: pc_mac
      remoteRef:
        key: home-assistant/pc-power
        property: pc_mac
    - secretKey: pc_host
      remoteRef:
        key: home-assistant/pc-power
        property: pc_host
    - secretKey: pc_broadcast
      remoteRef:
        key: home-assistant/pc-power
        property: pc_broadcast
    - secretKey: pc_ssh_host
      remoteRef:
        key: home-assistant/pc-power
        property: pc_ssh_host
    - secretKey: pc_ssh_user
      remoteRef:
        key: home-assistant/pc-power
        property: pc_ssh_user
    - secretKey: pc_ssh_private_key
      remoteRef:
        key: home-assistant/pc-power
        property: pc_ssh_private_key
    - secretKey: pc_sleep_cmd
      remoteRef:
        key: home-assistant/pc-power
        property: pc_sleep_cmd
