apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-manager-api
  labels:
    app: ingress-manager-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-manager-api
  template:
    metadata:
      labels:
        app: ingress-manager-api
    spec:
      serviceAccountName: ingress-manager-sa
      imagePullSecrets:
      - name: harbor-creds
      containers:
      - name: api
        image: harbor.devflux.ru/devops-tools/ingress-manager-api:17
        imagePullPolicy: Always
        command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: ingress-manager-config
        - secretRef:
            name: ingress-manager-secret
        - secretRef:
            name: ingress-manager-db
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
