apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  namespace: monitoring
  labels:
    app: uptime-kuma
    environment: monitoring
    component: uptime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
